### ISSUE TITLE
Migrate All of Lookup to SHOW in Snowflake

### ISSUE THREAD

**Issue by norton120** [Health-Union/snowshu#47]
## Why? 
Snowflake object introspection via traditional information_schema lookup is janky, slow, expensive, and occasionally returns the dreaded "too much data" error. Moving all the object lookups to SHOW commands is a better long-term solution.

## Who does this impact? 
- every Snowflake user that wants faster, more reliable SnowShu runs. 

**Note**: will probably require that we clobber several base adapter internals, so this is as good a time as any to standardize and break them out.

**Comment by eculicny** [comment]
Due to the limits on snowflake's SHOW command (max 10K rows) and the ability to select all objects on a server via regex in the configuration, using SHOW COLUMN command at a table/view level could now require numerous extra network calls for large databases. Switching to a schema level could easily run over the 10K row return limit.

I'm currently working on a way to filter the databases and schemas before building the catalog instead of retrieving the details for the entire server/instance before filtering. Querying INFORMATION_SCHEMA by both database and schema should help avoid the "too much data" error.

If there is still too much latency or "too much data", we can add another level down to build the INFORMATION_SCHEMA queries based on the specific tables and views that match the configuration.
